### PR TITLE
Add examine option

### PR DESCRIPTION
**Pull request by Jbleezy**
Adds the option to show examine instead of info menu entry which displays the pet's examine text.

Adds the option to toggle the pet's owner name.

Fixed pet's owner name being grey instead of white when on white color setting.

Moved menu entry to the bottom like how examine should be.

To make the examine entries, I used the most recent version of PetJsonCreator but it looks like pets.json got updated after without PetJsonCreator being updated, so PetJsonCreator and pets.json might need to be updated.

Whenever a new pet is added, the examine field now must also be added in PetJsonCreator.

[Config](https://imgur.com/a/jFlgjQR)

### CODE REVIEW

**Comment by microtavor5** [comment]
Looks like at the moment there is only the option to either to have an "info" or an "examine" menu option. What are your thoughts on allowing for both if the player wanted?

**Comment by Jbleezy** [comment]
Sure, you want to add that?

**Comment by microtavor5** [comment]
Sure, my current to do list with this merge is basically

- Add the option for both examine and info
- Add the new pets that have come out
- Test that it all works
- Test that merging the new JSON to main won't break the plugin for people using an old version while we wait for the new version to be accepted

I'm happy to do it all, when I have free time. I'll need to use my reserve bond for testing since I let my membership laps lol

**Comment by Jbleezy** [comment]
Ok, yeah I have also taken a break from OSRS lol.

**Comment by microtavor5** [comment]
So I updated it to have the ability to do both info and examine, as well as added the examine text for the new pet.
Could you do me a favor? As a sanity check could you spin up a copy of the main plugin but tell it to pull the JSON from the examine-option branch instead?
I did it on my machine and everything worked fine, I had the Info option and it didn't crash, but I would like a second opinion before I make a change that could break the plugin for all users..

To do it you just need to change the URL in `PetDataFetcher.java`
from `https://raw.githubusercontent.com/microtavor5/PetInfoPlugin/master/pets.json`
to `https://raw.githubusercontent.com/microtavor5/PetInfoPlugin/examine-option/pets.json`

Also:
image
lol

**Comment by Jbleezy** [comment]
Looks good to me!

**Comment by microtavor5** [comment]
So I merged the code in with my own pull request because github is black magic, I'll submit it for review by the fine folks over at runelite

**Pull request closed without merging**
